mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path, re_path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'questions', views.QuestionSerializer)


app_name = 'polls'
urlpatterns = [
    path('api/', include(router.urls)),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detalle'),
    path('<int:pk>/vote/', views.vote, name='vote'),
    path('<int:pk>/resultado/', views.ResultsView.as_view(), name='resultado'),
]

mysite/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

from .models import Question,Choice
from django.template import loader
from django.urls import reverse
from django.views import generic


# def index(request):
#     # ORM pedir preguntas
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list
#         }
#     return render(request, 'polls/index.html', context)

# Esto es herencia multiple para que herede las demas clases model y context_object_name
class CosasDePreguntas(generic.DetailView):
    model = Question
    context_object_name = 'encuesta'

# No puede heredar porque esta haciendo una ListView
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    paginate_by = 2


    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:20]


class DetailView(CosasDePreguntas):
    # model = Question
    template_name = 'polls/detalle.html'
    # context_object_name = 'encuesta'


class ResultsView(CosasDePreguntas):
    # model = Question
    template_name = 'polls/resultado.html'
    # context_object_name = 'encuesta'


def vote(request, pk):
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice = question.options.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detalle.html', {
            'encuesta': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # return HttpResponseRedirect(f"/polls/{question.id}/resultado/")
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:resultado', args=(question.id,)))

from rest_framework import viewsets
from .serializer import QuestionSerializer
from rest_framework import serializers
# from django.contrib.auth.models import User

class QuestionSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']




# def detalle(request, id):
#     # Pide al ORM la pregunta con ese id
#     # Y si no la encuentra levanta una excepcion 404
#     encuesta = get_object_or_404(Question, pk=id)
#     return render(
#         request,
#         'polls/detalle.html',
#         {
#             'encuesta': encuesta
#         }
#     )

# def vote(request, id):
#     question = get_object_or_404(Question, pk=id)
#     try:
#         selected_choice = question.options.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detalle.html', {
#             'encuesta': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # return HttpResponseRedirect(f"/polls/{question.id}/resultado/")
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:resultado', args=(question.id,)))

# def resultado(request, id):
#     question = get_object_or_404(Question, pk=id)
#     return render(request, 'polls/resultado.html',{
#         'encuesta':question
#     })

mysite/polls/templates/polls/detalle.html
<form action="{% url 'polls:vote' encuesta.pk %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend>
            <h1>{{ encuesta.question_text }}</h1>
            <h3>{{ encuesta.pub_date }}</h3>
        </legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in encuesta.options.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>
<a href="{% url 'polls:index' %}">listado</a>
<a href="{% url 'polls:detalle' encuesta.pk %}">Volver a votar</a>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
<h1>Esta es la seccion de encuestas</h1>
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detalle' question.pk %}">{{ question.question_text }}</a></li>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </ul>
{% else %}
    <p>No polls</p>
{% endif %}

mysite/polls/templates/polls/resultado.html
<h1>{{ encuesta.question_text }}</h1>
<h2> {{ encuesta.pub_date }}</h2>
<div>
    <ul>
        {% for o in encuesta.options.all %}
        <li>{{ o.choice_text }}  ({{o.votes}})</li>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'polls:index' %}">listado</a>
<a href="{% url 'polls:detalle' encuesta.pk %}">Volver a votar</a>